name: Update Categories referential

on:
  schedule:
    # At 06:00 on Monday
    - cron: '0 6 * * 1'

jobs:
  update-referential:
    name: Update Categories referential
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Update referential
        env:
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NEXT_API_BEARER_TOKEN: ${{ secrets.NEXT_API_BEARER_TOKEN }}
        run: |
          cd scripts
          npm ci
          node update-categories-referential.mjs
          cd ..
          git checkout -b chore/update_categories_referential

      - name: Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "ðŸŒ± Update Categories referential"
          git push -f --set-upstream origin chore/update_categories_referential

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'ðŸŒ± Update Categories referential',
              owner,
              repo,
              head: 'chore/update_categories_referential',
              base: 'main',
              body: [
                'This is an automated PR.',
                'It updates the referential with categories data.'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['automated pr', 'referential']
            });
            github.rest.pulls.requestReviewers({
              owner,
              repo,
              pull_number: result.data.number,
              reviewers: ['benjaminbrgs', 'ZenikAdrien', 'MailyLehoux']
            });
